# -*- coding: utf-8 -*-

strings = [
    ["relation_field_error",
        "Deletion is not possible due to dependence on other entities."],
    ["duplicated_field_error",
        "Changes are not possible due to the duplicate field."],
    ["remove_admin_error",
        "You can not delete your account."],
    ["remove_main_admin_error",
        "You can not delete the main administrator account."],
    ["remove_admin_access_error",
        "You cannot take management access from you."],
    ["your_activation_code_title",
        "Your activation code"],
    ["your_activation_code_message",
        "Your activation code to log in to your user account: %s"],
    ["insufficient_access_level_error",
        "Your access level is not enough to use this section."],
    ["invalid_token_error",
        "Your token is invalid."],
    ["recover_passsword_title",
        "Password recovery"],
    ["recover_passsword_message",
        "Use this address to recover your account password: %s"],
    ["your_account_is_disabled_error",
        "Your account has been deactivated."],
    ["not_have_access_error",
        "You do not have access to this section."],
    ["your_activation_status_title",
        "Account status"],
    ["your_activation_confirmed_message",
        "Your account has been verified."],
    ["your_activation_rejected_message",
        "Your account has been rejected."],
    ["image_size_error",
        "Image size must be less than 1000 pixels."],
    ["package_conflict_error",
        "This package overlaps with another package."],
    ["package_order_error",
        "The end of the package cannot be before the start of the package."],
    ["time_box_conflict_error",
        "This time box overlaps with another time box."],
    ["time_box_order_error",
        "The end of the time box cannot be before the start of the time box."],
    ["meeting_conflict_error",
        "This meeting overlaps with another meeting."],
    ["meeting_order_error",
        "The end of the meeting cannot be before the start of the meeting."],
    ["meeting_time_box_not_found_error",
        "The psychiatrist does not provide the service at this time."],
    ["meeting_status",
        "Meeting status"],
    ["accepted_meeting_message",
        "%s accepted the meeting with you."],
    ["rejected_meeting_message",
        "%s rejected the meeting with you."],
    ["completed_meeting_message",
        "%s completed the meeting with you."],
    ["needs_payment_error",
        "To create this session, first charge your account."],
    ["your_response_are_invalid",
        "Your responses are invalid, please try again."]
]


def localize(id):
    for item in strings:
        if item[0] == id:
            return item[1]
    return None
